// components/navbar.jsx
import Link from 'next/link';
import useAuth from '../hooks/use-auth';

export default function Navbar() {
    const auth = useAuth();

    return (
        <div className="navbar rounded-box p-0">
            <div className="flex-1">
                <Link href="/" className="link no-underline text-white text-4xl font-bold p-0">
                    Tink!
                </Link>
            </div>
            <div className="flex-none">
                <div className="dropdown dropdown-end">
                    <label tabIndex={0} className="btn btn-ghost btn-circle avatar flex">
                        <div className="w-10 rounded-full bg-primary text-white text-2xl font-bold leading-10">
                            {auth.user && (auth.user.fullname?.charAt(0) || auth.user.username?.charAt(0))}
                        </div>
                    </label>
                    <ul
                        tabIndex={0}
                        className="menu menu-compact dropdown-content mt-2 p-2 shadow bg-base-100 rounded-box w-52"
                    >
                        <li>
                            <a>Profile</a>
                        </li>
                        <li>
                            <Link href="/logout">Logout</Link>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    );
}

// components/Navbar.vue
<script lang="ts" setup>
const user = useAuthUser();
</script>

<template>
    <div class="navbar rounded-box p-0">
        <div class="flex-1">
            <NuxtLink to="/" class="link no-underline text-white text-4xl font-bold p-0">Tink!</NuxtLink>
        </div>
        <div class="flex-none">
            <div v-if="user" class="dropdown dropdown-end">
                <label tabindex="0" class="btn btn-ghost btn-circle avatar flex">
                    <div class="w-10 rounded-full bg-primary text-white text-2xl font-bold leading-10">
                        {{ user.fullname.charAt(0) || user.username.charAt(0) }}
                    </div>
                </label>
                <ul
                    tabindex="0"
                    class="menu menu-compact dropdown-content mt-2 p-2 shadow bg-base-100 rounded-box w-52"
                >
                    <li>
                        <a>Profile</a>
                    </li>
                    <li>
                        <NuxtLink to="/logout">Logout</NuxtLink>
                    </li>
                </ul>
            </div>
            <NuxtLink v-else to="/login" class="btn btn-primary">Login</NuxtLink>
        </div>
    </div>
</template>
