// pages/password/update.jsx
import { useState } from 'react';
import Guard from '../../components/guard';
import useAxios from '../../hooks/use-axios';

export default function UpdatePasswordPage() {
    const axios = useAxios();
    const [loading, setLoading] = useState(false);
    const [password, setPassword] = useState('');
    const [password2, setPassword2] = useState('');
    const handleSubmit = e => {
        setLoading(true);
        e.preventDefault();

        axios
            .patch('/profile/password', { password, password_confirm: password2 })
            .then(res => {
                console.log(res.data.message);
            })
            .finally(() => setLoading(false));
    };

    return (
        <Guard>
            <div className="hero min-h-screen">
                <div className="hero-content flex-col lg:flex-row-reverse w-full max-w-sm">
                    <div className="text-center lg:text-left w-full max-w-80">
                        <h1 className="text-5xl font-bold">Please Update Your Password</h1>
                    </div>
                    <div className="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
                        <form onSubmit={handleSubmit} className="card-body">
                            <div className="form-control">
                                <label className="label">
                                    <span className="label-text">New Password</span>
                                </label>
                                <input
                                    value={password}
                                    onInput={e => setPassword(e.target.value)}
                                    type="password"
                                    className="input input-bordered"
                                />
                            </div>
                            <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Repeat Password</span>
                                </label>
                                <input
                                    value={password2}
                                    onInput={e => setPassword2(e.target.value)}
                                    type="password"
                                    className="input input-bordered"
                                />
                            </div>
                            <div className="form-control mt-6">
                                {loading ? (
                                    <button className="btn btn-primary loading"></button>
                                ) : (
                                    <button className="btn btn-primary" type="submit">
                                        Update
                                    </button>
                                )}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </Guard>
    );
}

// pages/password/update.vue
<script lang="ts" setup>
definePageMeta({ layout: 'clear' });
const message = useMessage();
const loading = useLoading();
const password1 = ref('');
const password2 = ref('');

async function handleSubmit() {
    if (password1.value.length < 6) {
        return (message.value = 'Minimal password length is 6 characters');
    }
    if (password1.value != password2.value) {
        return (message.value = 'The password confirmation does not match');
    }

    const { data, error } = await useApi('/profile/password', {
        method: 'PATCH',
        body: {
            password: password1.value,
            password_confirm: password2.value,
        },
    });

    // ! temp
    await useAuthFetch().refresh();
}
function protectPage() {
    return useAuthUser().value?.limited;
}
</script>

<template>
    <Guard :custom="protectPage">
        <div class="hero min-h-screen">
            <div class="hero-content flex-col lg:flex-row-reverse w-full max-w-sm">
                <div class="text-center lg:text-left w-full max-w-80">
                    <h1 class="text-5xl font-bold">Please Update Your Password</h1>
                </div>
                <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
                    <form @submit.prevent="handleSubmit" class="card-body">
                        <div class="form-control">
                            <label class="label">
                                <span class="label-text">New Password</span>
                            </label>
                            <input v-model="password1" type="password" class="input input-bordered" required />
                        </div>
                        <div class="form-control mb-4">
                            <label class="label">
                                <span class="label-text">Repeat Password</span>
                            </label>
                            <input v-model="password2" type="password" class="input input-bordered" required />
                        </div>

                        <div class="form-control">
                            <button class="btn btn-primary" type="submit" :class="{ loading }">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </Guard>
</template>
