// pages/login.vue
<script lang="ts">
definePageMeta({
    layout: 'clear',
});
</script>
<template>
    <div class="hero min-h-screen">
        <div class="hero-content flex-col w-full max-w-sm">
            <div class="text-center lg:text-left">
                <h1 class="text-6xl font-bold">Tink!</h1>
            </div>
            <div class="card w-full flex-shrink-0 shadow-2xl bg-base-100">
                <form class="card-body">
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text">Username</span>
                        </label>
                        <input type="text" class="input input-bordered" name="username" required />
                    </div>
                    <div class="form-control mb-4">
                        <label class="label">
                            <span class="label-text">Password</span>
                        </label>
                        <input type="password" class="input input-bordered" name="password" />
                        <label class="label">
                            <NuxtLink to="/password/forgot" class="label-text-alt link link-hover">
                                Forgot password?
                            </NuxtLink>
                        </label>
                    </div>
                    <div class="form-control">
                        <button class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>

// pages/login.jsx
import Link from 'next/link';

export default function LoginPage() {
    return (
        <div className="container max-w-6xl">
            <div className="hero min-h-screen bg-base-200">
                <div className="hero-content flex-col w-full max-w-sm">
                    <div className="text-center lg:text-left">
                        <h1 className="text-6xl font-bold">Tink!</h1>
                    </div>
                    <div className="card w-full flex-shrink-0 shadow-2xl bg-base-100 ">
                        <div className="card-body ">
                            <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Username</span>
                                </label>
                                <input type="text" className="input input-bordered" />
                            </div>
                            <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Password</span>
                                </label>
                                <input type="text" className="input input-bordered" />
                                <label className="label">
                                    <Link href="/forgot-password" className="label-text-alt link link-hover">
                                        Forgot password?
                                    </Link>
                                </label>
                            </div>
                            <div className="form-control mt-6">
                                <button className="btn btn-primary">Login</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
